### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by adamwlev** [Giqles/kagglegym#1]
Hi, thanks very much. I have the follow issue:

I built with:

`sudo docker build -t kagglegym .`

Then when I try:

`sudo docker run -it -m=5G -v $(pwd):/wd kagglegym` it works fine but in trying to launch a jupyter notebook I get the following error:

PermissionError: [Errno 13] Permission denied: '/home/kaggler/.jupyter'

With the following traceback:
/opt/conda/lib/python3.5/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/kaggler' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1065, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 169, in migrate_config
    migrate()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)

This error persists with either trying to launch a notebook from the command line with the command suggested in the README and with the jupyter notebook command inside the container. It also persists whether or not I use sudo.

Thanks again.

**Comment by adamwlev** [comment]
Also I'd just like to add, this error was not occurring two days ago when I first built. I was encountering memory capping and trying to troubleshoot this so I was rebuilding and the error occurred. It must have something to do with a recent commit?

**Comment by Giqles** [comment]
I'm not able to recreate this error - is your clone completely up to date? I was messing around with directories yesterday to fix an issue with joblib, perhaps you caught it in a broken state. If that's not the problem let me know what OS you're running etc and I'll try and help out.

**Comment by gp7029** [comment]
Ok. so now I'm getting the same error as well. I tried building on my laptop(windows 10) and my server (centos 7). same thing. Any suggestions?

**Comment by Giqles** [comment]
Which version of docker are you running?

**Comment by gp7029** [comment]
1.12.5

**Comment by gp7029** [comment]
found the solution. I commented out the "USER kaggler" line in docker file!

**Comment by stfods** [comment]
Got pretty same error on container start:
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.5/site-packages/SimpleITK-0.10.0-py3.5.egg-info'

Resolved that by modifying Docker file by increasing permissions level for kaggler user

**Comment by Giqles** [comment]
@stfods, can you pull-request the fix please?
